controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.5 #0.5
  min_vel_x: 0.01 #0.01
  min_vel_y: 0
  max_vel_y: 0

  acc_lim_theta: 3.14
  acc_lim_x: 2.0

  sim_time: 3.0

  vx_samples: 3.0 #3.0
  vtheta_samples: 20.0 #20.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.5 #0.8
  occdist_scale: 0.03 #0.01
  heading_lookahead: 0.8 #0.325
  heading_score: true

  publish_cost_grid_pc: true

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.6

  dwa: false
  meter_scoring: true

