controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 1.0 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_theta: 1.57 #1.5
  max_vel_y: 0.0 

  min_in_place_vel_theta: -0.157

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 2.0

  vx_samples: 3.0 #3.0
  vtheta_samples: 10.0 #20.0

  pdist_scale: 35.0 #0.6
  gdist_scale: 15.0 #0.8
  occdist_scale: 0.02 #0.01
  heading_lookahead: 0.325 #0.325


  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.6

  path_distance_bias: 35.0
  goal_distance_bias: 15.0


  dwa: false
  meter_scoring: true

  holonomic_robot: false
