map_type: costmap

obstacle_range: 2.0 # 2.0
raytrace_range: 3.0 # 3.0

transform_tolerance: 0.0 # 0.0

robot_footprint: [[0.2,0.4], [-0.2,0.4], [-0.2,-0.4], [0.2, -0.4]]
#robot_radius: 0.6 # 0.0
inflation_radius: 0.6 # 0.0
cost_scaling_factor: 23.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
